package edu.exampro.db;

import edu.exampro.exception.ExamException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/** Opens JDBC connections to the embedded H2 database stored in ./data. */
public final class Database {
    // The _v2 name keeps this version away from the old schema created by the first version.
    private static final String URL = "jdbc:h2:./data/exampro_v2;AUTO_SERVER=TRUE";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private Database() { }

    /** Every caller gets its own connection, so connections are never shared between threads. */
    public static Connection connection() {
        try {
            return DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (SQLException exception) {
            throw new ExamException("Could not connect to database", exception);
        }
    }

    /** Reads the id generated by the last INSERT executed on this statement. */
    public static long generatedKey(PreparedStatement statement) throws SQLException {
        try (ResultSet keys = statement.getGeneratedKeys()) {
            if (!keys.next()) {
                throw new SQLException("The database did not return a generated id");
            }
            return keys.getLong(1);
        }
    }
}
