package edu.exampro.db;

import edu.exampro.exception.ExamException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/** Creates the schema on first run. Safe to run again (CREATE TABLE IF NOT EXISTS). */
public final class DatabaseInitializer {
    private static final List<String> SCHEMA = List.of(
        """
        CREATE TABLE IF NOT EXISTS students (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            email VARCHAR(160) NOT NULL UNIQUE,
            registration_number VARCHAR(60) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS exams (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(200) NOT NULL,
            duration_minutes INT NOT NULL CHECK (duration_minutes > 0)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS questions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_id BIGINT NOT NULL,
            question_type VARCHAR(10) NOT NULL,
            prompt VARCHAR(1000) NOT NULL,
            marks INT NOT NULL CHECK (marks > 0),
            correct_option INT NOT NULL,
            FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS question_options (
            question_id BIGINT NOT NULL,
            option_index INT NOT NULL,
            option_text VARCHAR(500) NOT NULL,
            PRIMARY KEY (question_id, option_index),
            FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS attempts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_id BIGINT NOT NULL,
            student_id BIGINT NOT NULL,
            score INT NOT NULL,
            submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
            UNIQUE (exam_id, student_id),
            FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
            FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS answers (
            attempt_id BIGINT NOT NULL,
            question_id BIGINT NOT NULL,
            selected_option INT NOT NULL,
            PRIMARY KEY (attempt_id, question_id),
            FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
            FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS app_users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name VARCHAR(120) NOT NULL,
            email VARCHAR(160) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            role VARCHAR(20) NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT TRUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS exam_sessions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_id BIGINT NOT NULL,
            student_id BIGINT NOT NULL,
            start_time TIMESTAMP WITH TIME ZONE NOT NULL,
            UNIQUE (exam_id, student_id),
            FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
            FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
        )
        """
    );

    private DatabaseInitializer() { }

    public static void initialize() {
        try (Connection connection = Database.connection();
             Statement statement = connection.createStatement()) {
            for (String sql : SCHEMA) {
                statement.execute(sql);
            }
        } catch (SQLException exception) {
            throw new ExamException("Could not create database schema", exception);
        }
    }
}
